---
- name: Set up greeneagle loadbalancer networking
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/zone
  tasks:

  - name: create a global address for greeneagle
    gcp_compute_global_address:
        name: "ge-globaladdress-globalforwardingrule1"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
    register: ge_globaladdress

  - name: create a greeneagleapp instance group
    gcp_compute_instance_group:
        name: "ge-instancegroup-globalforwardingrule"
        zone: "{{ zone.za }}"
        instances:
          - "{{ greeneagleappinstance1 }}"
          - "{{ greeneagleappinstance2 }}"
        named_ports:
        - name: http
          port: 80
        network: "{{ network }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
    register: greeneagleapp_ig

  - name: create a http health check
    gcp_compute_http_health_check:
        name: "httphealthcheck-greeneagle"
        healthy_threshold: 10
        port: 80
        timeout_sec: 2
        unhealthy_threshold: 5
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
    register: greeneagleapp_hc

  - name: create a backend greeneagle app service
    gcp_compute_backend_service:
        name: "greeneagle-bes-globalforwardingrule"
        backends:
        - group: "{{ greeneagleapp_ig.selfLink }}"
        health_checks:
        - "{{ greeneagleapp_hc.selfLink }}"
        enable_cdn: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
    register: greeneagleapp_bes
    ignore_errors: yes

  - name: create a url map greeneagle
    gcp_compute_url_map:
        name: "ge-urlmap-globalforwardingrule"
        default_service: "{{ greeneagleapp_bes }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
    register: geurlmap

  - name: create a target http proxy
    gcp_compute_target_http_proxy:
        name: "ge-httpproxy-globalforwardingrule"
        url_map: "{{ geurlmap }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
    register: ge_httpproxy

  - name: create a global forwarding rule
    gcp_compute_global_forwarding_rule:
        name: "ge-globalfowardingrule"
        ip_address: "{{ ge_globaladdress.address }}"
        load_balancing_scheme: "EXTERNAL"
        ip_protocol: TCP
        port_range: 80-80
        target: "{{ ge_httpproxy.selfLink }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
    register: geforwardingrule

  post_tasks:
    - debug:
        msg: "Load balancer IP: {{ geforwardingrule['IPAddress'] }}"
