---
- name: Create greeneagle instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: create a disk mapped for Greeneagle App instance 1 - Centos 8
      gcp_compute_disk:
        name: greeneagle-disk-instance1
        size_gb: 50
        type: pd-ssd
        source_image: "{{ image }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: ge_disk_instance1

    - name: create a disk mapped for Greeneagle App instance 2 - Centos 8
      gcp_compute_disk:
        name: greeneagle-disk-instance2
        size_gb: 50
        type: pd-ssd
        source_image: "{{ image }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: ge_disk_instance2
    
    - name: create a VPC stockcheck network
      gcp_compute_network:
        name: stockchecker-subnetwork
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network


    - name: create a firewall rules for greeneagle app
      gcp_compute_firewall:
        name: greeneagleapp-fw-ports
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        target_tags:
          - greeneagle
        source_tags:
          - management
          - stockcheck
          - redis
          - elasticsearch
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: gefirewall

    - name: create the greeneagle app instance 1
      gcp_compute_instance:
        name: "{{ ge_zonea }}"
        machine_type: "{{ machine_type.greeneagle }}"
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ ge_disk_instance1 }}"
        labels:
          environment: greeneagleprod
        network_interfaces:
          - network: "{{ network }}"
        tags:
          items:
            - greeneagle
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: greeneagleappinstance1

    - name: create the greeneagle app instance 2
      gcp_compute_instance:
        name: "{{ ge_zoneb }}"
        machine_type: "{{ machine_type.greeneagle }}"
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ ge_disk_instance2 }}"
        network_interfaces:
          - network: "{{ network }}"
        tags:
          items:
            - greeneagle
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: greeneagleappinstance2


    - debug: var=greeneagleappinstance1.networkInterfaces[0].networkIP
    - debug: var=greeneagleappinstance2.networkInterfaces[0].networkIP

    - name: Add instance1 to group greeneagleerapp
      add_host:
        name: "{{ greeneagleappinstance1.networkInterfaces[0].networkIP }}"
        groups: greeneagleerapp

    - name: Add instance2 to group greeneagleerapp
      add_host:
        name: "{{ greeneagleappinstance2.networkInterfaces[0].networkIP }}"
        groups: greeneagleerapp

  post_tasks:
    - name: Wait for SSH for instance1
      wait_for:
        delay: 30
        host: "{{ greeneagleappinstance1.networkInterfaces[0].networkIP }}"
        port: 22
        state: started
        timeout: 120

    - name: Wait for SSH for instance2
      wait_for:
        delay: 30
        host: "{{ greeneagleappinstance2.networkInterfaces[0].networkIP }}"
        port: 22
        state: started
        timeout: 120

- hosts: greeneagleerapp
  roles:
    - apache
   #- greeneagleapp
  gather_facts: False
  become: true
  vars:
    ansible_user: belloau
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.pub
  tasks:
    - name: ensuring webroot directory
      file:
        path: /var/www/html/frontend/web
        state: directory
        mode: '0755'

