---
- name: Create Master instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: create a disk mapped for Redis Node - Centos 8
      gcp_compute_disk:
        name: redis1-disk-instance
        size_gb: 50
        source_image: "{{ image }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk

    - name: create a data disk for Redis Node - Centos 8
      gcp_compute_disk:
        name: redis1-disk-data
        size_gb: 50
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk_data

    - name: create a VPC network
      google.cloud.gcp_compute_network:
        name: eagle-subnetwork
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network

    - name: create a firewall rules for VPC
      google.cloud.gcp_compute_firewall:
        name: eagle-fw-ports
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        target_tags:
          - management
        source_ranges:
          - '0.0.0.0/0'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: redis-instance1-ip
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: address

    - name: create the Redis instance
      gcp_compute_instance:
        name: redis1-instance1
        machine_type: "{{ machine_type }}"
        disks:
          - index: 0
            auto_delete: 'true'
            boot: 'true'
            source: "{{ disk }}"
          - index: 1
            auto_delete: 'true'
            source: "{{ disk_data }}"
            type: PERSISTENT
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - management
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: instance

    - name: Show Redis Instance Details
      debug:
        msg: "The Redis instance is accessible at {{ address.address }}"

    - name: Add redis1 to group redis1
      add_host:
        name: "{{ address.address }}"
        groups: redis

  post_tasks:
    - name: Wait for SSH for instances in first zone
      wait_for: delay=10 host={{ address.address }} port=22 state=started timeout=30

- hosts: redis
  gather_facts: False
  become: true
  vars:
    ansible_user: belloau
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.pub
    redis_pass: Xxhbyd5z
    pkgs:
      - redis
  tasks:
    - name: installing Redis
      dnf:
        name: "{{ pkgs }}"
        state: present

    - name: Redis Configuration
      template:
        src: templates/redis.j2
        dest: /etc/redis.conf

    - name: starting Redis services
      systemd:
        name: redis
        state: started
        enabled: yes

    - name: open Redis ports on firewalld
      firewalld:
        port: 6379/tcp
        permanent: yes
        state: enabled
        immediate: true

  handlers:
    - name: restart redis
      systemd:
        state: restarted
