---
- name: Getting master info instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: get info on master instance
      gcp_compute_instance_info:
        filters:
        - name = master
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: master
      #- debug: var=master.resources[0].networkInterfaces[0].networkIP

    - name: Adding Master instance to group master
      add_host:
        name: "{{ master.resources[0].networkInterfaces[0].networkIP }}"
        groups: master
    
    - name: get info on shoplauncher01 instance1
      gcp_compute_instance_info:
        filters:
        - name = shoplauncher01
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: shoplauncher01
    - debug: var=shoplauncher01.resources[0].networkInterfaces[0].networkIP

    - name: get info on shoplauncher02 instance2
      gcp_compute_instance_info:
        filters:
        - name = shoplauncher02 
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: shoplauncher02
    - debug: var=shoplauncher02.resources[0].networkInterfaces[0].networkIP

    - name: get info on shoplauncher03 instance3
      gcp_compute_instance_info:
        filters:
        - name = shoplauncher03 
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: shoplauncher03
    - debug: var=shoplauncher03.resources[0].networkInterfaces[0].networkIP

    - name: Adding shoplauncher01 instance to group stockcheck
      add_host:
        name: "{{ shoplauncher01.resources[0].networkInterfaces[0].networkIP }}"
        groups: shoplauncher
    
    - name: Adding shoplauncher02 instance to group stockcheck
      add_host:
        name: "{{ shoplauncher02.resources[0].networkInterfaces[0].networkIP }}"
        groups: shoplauncher

    - name: Adding shoplauncher03 instance to group stockcheck
      add_host:
        name: "{{ shoplauncher03.resources[0].networkInterfaces[0].networkIP }}"
        groups: shoplauncher


- hosts: shoplauncher
  gather_facts: true
  become: true
  vars:
    ansible_user: belloau
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.pub
  roles:
    - systemtools
    - apache
    - mariadb
  tasks:
    - name: copying keys for manyondoma
      authorized_key:
        user: mndoma 
        key: "{{ lookup('file', '/data/keys/id_mndoma.pub') }}"
    
    - name: copying keys for chukwudi
      authorized_key:
        user: chukwudi
        key: "{{ lookup('file', '/data/keys/id_chukwudi.pub') }}"
        state: present

    - name: adding sudoers for webadmin
      template:
        src: templates/webadmin_sudoers.j2
        dest: /etc/sudoers.d/webadmin_sudoers

    - name: adding sudoers for webadmin
      template:
        src: templates/sysadmin_sudoers.j2
        dest: /etc/sudoers.d/sysadmin_sudoers

    - name: ensuring webroot directory
      file:
        path: /var/www/html/frontend/web
        state: directory
        mode: '0755'

    - name: update apache configs
      template:
        src: templates/shoplauncher/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify: restart apache
        
    - name: Install PHPFM repos
      dnf:
        name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
        disable_gpg_check: True
        state: present

    - name: Enable the PHPFM repos
      dnf:
        name: "@php:remi-7.4"
        state: present

    - name: Installing PHP packages
      dnf:
        name:
          - php
          - php-fpm
          - php-gd
          - php-mysqlnd
        state: present

    - name: Starting the Php-fpm service
      systemd:
        name: php-fpm
        state: started
        enabled: yes
    
    - name: Installing compose PHP
      script: templates/shoplauncher/scripts/compose.sh
      register: compose

    - debug: var=compose


  handlers:
    - name: restart apache
      systemd:
        name: httpd
        state: restarted
